name: Run Discord Bot (manual)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: |
        curl -fsSL https://deb.nodesource.com/setup_23.x | sudo -E bash -
        sudo apt-get install -y nodejs
      name: Install Node.js manually

    - run: npm install
      name: Install dependencies

    - run: node deploy-commands.js
      name: Deploy commands
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - run: node main.js
      name: Start the bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
